### ISSUE TITLE
[Bug] Game of Life leaks memory!

### ISSUE THREAD

**Issue by Olf0** [pulsar541/harbour-gameoflife#5]
Issue description:

*Game of Life* leaks memory, a whopping 90 MBytes after about an hour of runtime.

Furthermore *Game of Life* made SailfishOS crashing (i.e., ultimately rebooting) when closdd at the GUI in this situation.  This may or may not be an additional bug.

**Comment by pulsar541** [comment]
It fixed

**Comment by Olf0** [comment]
Well, it is much better now.  Thanks!
I still haven not looked at the code, but the big memory leak is definitely fixed (almost looked like a new array is assigned each time the matrix of cells is newly calculated): Game of Life 0.4-1 does not continuously grab more memory while running, it even seems to free som memory every now and then (e.g. when turning the speed up and down).

Although still using 20 - 30 MBytes RAM ("RSS" = resident size) and 30 - 40% of  the CPU on a Jolla 1 (even when running Game of Life 0.4-1 at its lowest speed) is a lot.

Closing this issue, as the real memory leak is eliminated (and that is what this issue was about).
And do not worry too much about the still very high resource usage (since Game of Life is a nice fun-app, but seriously optimising it may be over-engineering), but if you have ideas how to further reduce RAM and CPU use easily, you might pursue them.
